# Generated by Django 6.0.3 on 2026-04-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.chat'),
        ),
    ]
