# Generated by Django 6.0.5 on 2026-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_user_current_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(to='messenger.media'),
        ),
    ]
