# Generated by Django 6.0.5 on 2026-05-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_media_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='filename',
        ),
    ]
